# Object Oriented Programming

## Agenda
1. Why a data scientist should learn about OOP
2. "Everything in Python is an object"  
3. Define attributes, methods, and dot notation
4. Describe the relationship of classes and objectes, and learn to code classes
5. Overview of Inheritance
6. Important data science tools through the lens of objects: Standard Scaler and One-Hot-Encoder

# 1. Why a data scientist should learn about OOP

![hackerman](https://media.giphy.com/media/MM0Jrc8BHKx3y/giphy.gif)

  - By becoming familiar with the principles of OOP, you will increase your knowledge of what's possible.  Much of what you might think you need to code by hand is already built into the objects.
  - With a knowledge of classes and how objects store information, you will develop a better sense of when the learning in machine learning occurs in the code, and after that learning occurs, how to access the information gained.
  - You become comfortable reading other people's code, which will improve your own code.
  - You will develop knowledge of the OOP family of programming languages, what are the strengths and weakness of Python, and the strengths and weaknesses of other language families.

  
Let's begin by taking a look at the source code for [Sklearn's standard scalar](https://github.com/scikit-learn/scikit-learn/blob/fd237278e/sklearn/preprocessing/_data.py#L517)

Take a minute to peruse the source code on your own.  



# 2. "Everything in Python is an object"  


Python is an object-oriented programming language. You'll hear people say that "everything is an object" in Python. What does this mean?

Go back to the idea of a function for a moment. A function is a kind of abstraction whereby an algorithm is made repeatable. So instead of coding:

In [1]:
print(3**2 + 10)
print(4**2 + 10)
print(5**2 + 10)

19
26
35


or even:

In [2]:
for x in range(3, 6):
    print(x**2 + 10)

19
26
35


I can write:

In [3]:
def square_and_add_ten(x):
    return x**2 + 10

Now imagine a further abstraction: Before, creating a function was about making a certain algorithm available to different inputs. Now I want to make that function available to different **objects**.

Even Python integers are objects. Consider:

In [4]:
x = 3

We can see what type of object a variable is with the built-in type operator:

In [5]:
type(x)

int

By setting x equal to an integer, I'm imbuing x with the methods of the integer class.

In [6]:
x.bit_length()

2

In [7]:
x.__float__()

3.0

In [8]:
x

3

Python is dynamically typed, meaning you don't have to instruct it as to what type of object your variable is.  
A variable is a pointer to where an object is stored in memory.

In [215]:
# interesting side note about how variables operate in Python

In [9]:
print(hex(id(x)))

0x10665e6c0


In [10]:
y = 3

In [11]:
print(hex(id(y)))

0x10665e6c0


In [12]:
# this can have implications 

x_list = [1,2,3,4]
y_list = x_list

x_list.pop()
print(x_list)
print(y_list)

[1, 2, 3]
[1, 2, 3]


In [13]:
# when you use copy(), you create a shallow copy of the object
z_list = y_list.copy()
y_list.pop()
print(y_list)
print(z_list)

[1, 2]
[1, 2, 3]


In [14]:
a_list = [[1,2,3], [4,5,6]]
b_list = a_list.copy()
a_list[0][0] ='z'
b_list

[['z', 2, 3], [4, 5, 6]]

In [15]:
import copy

#deepcopy is needed for mutable objects
a_list = [[1,2,3], [4,5,6]]
b_list = copy.deepcopy(a_list)
a_list[0][0] ='z'
b_list

[[1, 2, 3], [4, 5, 6]]

For more details on this general feature of Python, see [here](https://jakevdp.github.io/WhirlwindTourOfPython/03-semantics-variables.html).
For more on shallow and deepcopy, go [here](https://docs.python.org/3/library/copy.html#copy.deepcopy)

# 3. Define attributes, methods, and dot notation

Dot notation is used to access both attributes and methods.

Take for example our familiar friend, the [Pandas DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html)

In [16]:
import pandas as pd
# Dataframes are another type of object which we are familiar with.

df = pd.DataFrame({'price':[50,40,30],'sqft':[1000,950,500]})

In [17]:
type(df)

pandas.core.frame.DataFrame

Instance attributes are associated with each unique object.
They describe characteristics of the object, and are accessed with dot notation like so:

In [18]:
df.shape

(3, 2)

What are some other DataFrame attributes we know?:

In [19]:
# answer

In [20]:
#__SOLUTION__
# Other attributes
print(df.columns)
print(df.index)
print(df.dtypes)
print(df.T)

Index(['price', 'sqft'], dtype='object')
RangeIndex(start=0, stop=3, step=1)
price    int64
sqft     int64
dtype: object
          0    1    2
price    50   40   30
sqft   1000  950  500


A **method** is what we call a function attached to an object

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
price    3 non-null int64
sqft     3 non-null int64
dtypes: int64(2)
memory usage: 176.0 bytes


In [22]:
# isna() is a method that comes along with the DataFrame object
df.isna()

price   sqft
0  False  False
1  False  False
2  False  False

What other DataFrame methods do we know?

In [23]:
#__SOLUTION__
df.describe()
df.copy()
df.head()
df.tail()

price  sqft
0     50  1000
1     40   950
2     30   500

# Pair Exercise

Let's practice accessing the methods associated with the built in string class.  
You are given a string below: 

In [36]:
example = '   hELL0, w0RLD?   '

Your task is to fix is so it reads `Hello, World!` using string methods.  To practice chaining methods, try to do it in one line.
Use the [documentation](https://docs.python.org/3/library/stdtypes.html#string-methods), and use the inspect library to see the names of methods.

In [26]:
import inspect
inspect.getmembers(example)

[('__add__', <method-wrapper '__add__' of str object at 0x118bb8930>),
 ('__class__', str),
 ('__contains__',
  <method-wrapper '__contains__' of str object at 0x118bb8930>),
 ('__delattr__', <method-wrapper '__delattr__' of str object at 0x118bb8930>),
 ('__dir__', <function str.__dir__>),
 ('__doc__',
  "str(object='') -> str\nstr(bytes_or_buffer[, encoding[, errors]]) -> str\n\nCreate a new string object from the given object. If encoding or\nerrors is specified, then the object must expose a data buffer\nthat will be decoded using the given encoding and error handler.\nOtherwise, returns the result of object.__str__() (if defined)\nor repr(object).\nencoding defaults to sys.getdefaultencoding().\nerrors defaults to 'strict'."),
 ('__eq__', <method-wrapper '__eq__' of str object at 0x118bb8930>),
 ('__format__', <function str.__format__>),
 ('__ge__', <method-wrapper '__ge__' of str object at 0x118bb8930>),
 ('__getattribute__',
  <method-wrapper '__getattribute__' of str object at 

In [27]:
# we can also use built in dir() method
dir(example)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [37]:
# Your code here
example.replace('?', '!').swapcase().replace('0', 'o').strip()

'Hello, World!'

In [29]:
#__SOLUTION__
example.swapcase().replace('0','o').strip().replace('?','!')

'Hello, World!'

# 4. Describe the relationship of classes and objectes, and learn to code classes

Each object is an instance of a **class** that defines a bundle of attributes and functions (now, as proprietary to the object type, called *methods*), the point being that **every object of that class will automatically have those proprietary attributes and methods**.

A class is like a blueprint that describes how to create a specific type of object.

![blueprint](img/blueprint.jpeg)


## Classes

We can define **new** classes of objects altogether by using the keyword `class`:

In [36]:
class Car:
    """Automotive object"""
    pass # This called a stub. 

In [37]:
# Instantiate a car object
ferrari =  Car()
type(ferrari)

__main__.Car

In [39]:
# We can give describe the ferrari as having four wheels

ferrari.wheels = 4
ferrari.wheels

4

In [239]:
# But wouldn't it be nice to not have to do that every time? 
# We assume the blueprint of a car will have include the 4 wheels specification
# and assign it as an attribute when building the class

In [40]:
class Car:
    """Automotive object"""
    
    wheels = 4                      # These are attributes of *every* car.


In [41]:
civic = Car()
civic.wheels


4

In [43]:
#  Then we can add more attributes
class Car:
    """Automotive object"""
    
    wheels = 4                      # These are attributes of *every* car.
    doors = 4


In [46]:
ferrari = Car()
ferrari.doors


4

In [47]:
# But a ferrari does not have 4 doors! 
# These attributes can be overwritten 

ferrari.doors = 2
ferrari.doors

2

### Methods

We can also write functions that are associated with each class.  
As said above, a function associated with a class is called a method.

In [48]:
#  Then we can add more attributes
class Car:
    """Automotive object"""
    
    wheels = 4                      # These are attributes of *every* car.
    doors = 4

    def honk(self):                   # These are methods we can call on *any* car.
        print('Beep beep')
        
    

In [49]:
ferrari = civic = Car()
ferrari.honk()
civic.honk()


Beep beep
Beep beep


Wait a second, what's that `self` doing? 

## Magic Methods

It is common for a class to have magic methods. These are identifiable by the "dunder" (i.e. **d**ouble **under**score) prefixes and suffixes, such as `__init__()`. These methods will get called **automatically** as a result of a different call, as we'll see below.

For more on these "magic methods", see [here](https://www.geeksforgeeks.org/dunder-magic-methods-python/).

When we create an instance of a class, Python invokes the __init__ to initialize the object.  Let's add __init__ to our class.


In [52]:
#  Then we can add more attributes
class Car:
    """Automotive object"""
    
    WHEELS = 4                      # Capital letters mean wheels is a constant
    
    def __init__(self, doors, fwd):
        
        self.doors = doors
        self.fwd = fwd
        

    def honk(self):                   # These are methods we can call on *any* car.
        print('Beep beep')
    

By adding doors and moving to init, we need to pass parameters when instantiating the object.

In [54]:
civic = Car(4, True)
print(civic.doors)
print(civic.fwd)

4
True


We can also pass default arguments if there is a value for a certain parameter which is very common.

In [55]:
#  Then we can add more attributes
class Car:
    """Automotive object"""
    
    WHEELS = 4                     
    
    # default arguments included now in __init__
    def __init__(self, doors=4, fwd=False):
        
        self.doors = doors
        self.fwd = fwd
        

    def honk(self):                  
        print('Beep beep')
    

In [56]:
civic = Car()
print(civic.doors)
print(civic.fwd)

4
False


#### Positional vs. Named arguments

In [57]:
# we can pass our arguments without names
civic = Car(4, True)


In [58]:
# or with names
civic = Car(doors=4, fwd=True)


In [59]:
# or with a mix
civic = Car(4, fwd=True)


In [60]:
# but only when positional precides named
civic = Car(doors = 4, True)

SyntaxError: positional argument follows keyword argument (<ipython-input-60-6046029021d3>, line 2)

In [62]:
# The self argument allows our methods to update our attributes.

#  Then we can add more attributes
class Car:
    """Automotive object"""
    
    WHEELS = 4                     
    
    # default arguments included now in __init__
    def __init__(self, doors=4, fwd=False, driver_mood='peaceful'):
        
        self.doors = doors
        self.fwd = fwd
        self.driver_mood = driver_mood
        

    def honk(self):                  
        print('Beep beep')
        self.driver_mood = 'pissed'
    

In [63]:
civic = Car()
print(civic.driver_mood)
civic.honk()
print(civic.driver_mood)

peaceful
Beep beep
pissed


# Pair

 Let's bring our knowledge together, and in pairs, code out the following:

We have an attribute `moving` which indicates, with a boolean, whether the car is moving or not.  

Fill in the functions stop and go to change the attribute `moving` to reflect the car's present state of motion after the method is called.  Also, include a print statement that indicates the car has started moving or has stopped.

Make sure the method works by calling it, then printing the attribute.


In [64]:
#  Then we can add more attributes
class Car:
    """Automotive object"""
    
    # default arguments included now in __init__
    def __init__(self, doors=4, fwd=False, driver_mood='peaceful'):
        
        self.doors = doors
        self.fwd = fwd
        self.driver_mood = driver_mood
        
    def honk(self):                   # These are methods we can call on *any* car.
        print('Beep beep')
        
    def go(self):
        pass
    
    def stop(self):
        pass

In [65]:
#__SOLUTION__
class Car:
    """Automotive object"""
    WHEELS = 4
     # default arguments included now in __init__
    def __init__(self, doors=4, fwd=False, driver_mood='peaceful', moving=False):
        
        self.doors = doors
        self.fwd = fwd
        self.moving = moving
        self.driver_mood = driver_mood

    def honk(self):                   # These are methods we can call on *any* car.
        print('Beep beep')
        
    def go(self):
        self.moving = True
        print('Whoa, that\'s some acceleration!')
    
    def stop(self):
        self.moving = False
        print('Screeech!')

In [66]:
# run this code to make sure your 
civic = Car()
print(civic.moving)

civic.go()
print(civic.moving)

civic.stop()
print(civic.moving)

False
Whoa, that's some acceleration!
True
Screeech!
False


## 5. Overview of inheritance

We can also define classes in terms of *other* classes, in which cases the new classes **inherit** the attributes and methods from the classes in terms of which they're defined.

Suppose we decided we want to create an electric car class.

In [67]:
#  Then we can add more attributes
class ElectricCar(Car):
    """Automotive object"""
    
    pass

In [68]:
prius = ElectricCar()
prius.honk()
prius.WHEELS

Beep beep


4

In [69]:
#  Then we can add more attributes
class ElectricCar(Car):
    """Automotive object"""
    
    # default arguments included now in __init__
    def __init__(self, hybrid=False):
        super().__init__()
        self.hybrid = True 

In [70]:
#  And we can overwrite methods and parent attributes
class ElectricCar(Car):
    """Automotive object"""
    
    # default arguments included now in __init__
    def __init__(self, hybrid=False):
        
        # Prius owners are calmer than the average car owner
        super().__init__(driver_mood='serene')
        
        self.hybrid = True
        
    # overwrite inheritd methods
    
    def go(self):
        
        print('Whirrrrrr')
        self.moving = True

In [71]:
prius = ElectricCar()
print(prius.moving)
prius.go()
prius.moving
print(prius.driver_mood)

False
Whirrrrrr
serene


## 6. Important data science tools through the lens of objects: 

We are becomming more and more familiar with a series of methods with names such as fit or fit_transform.

After instantiating an instance of a Standard Scaler, Linear Regression model, or One Hot Encoder, we use fit to learn about the dataset and save what is learned. What is learned is saved in the attributes.

### 1. Standard Scaler 

The standard scaler takes a series and, for each element, computes the absolute value of the difference from the point to the mean of the series, and divides by the standard deviation.

$\Large z = \frac{|x - \mu|}{s}$

What attributes and methods are available for a Standard Scaler object? Let's check out the code on [GitHub](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/preprocessing/_data.py)!

## Attributes

### `.scale_`

In [72]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# instantiate a standard scaler object
ss = StandardScaler()

# We can instantiate as many scaler objects as we want
maxs_scaler = StandardScaler()

In [73]:
# Let's create a dataframe with two series

series_1 = np.random.normal(3,1,1000)
print(series_1.mean())
print(series_1.std())

2.9939080474222566
0.9723918679752294


When we fit the standard scaler, it studies the object passed to it, and saves what is learned in its instance attributes

In [75]:
ss.fit(series_1.reshape(-1,1))

# standard deviation is saved in the attribute scale_
ss.scale_

array([0.97239187])

In [76]:
# mean is saved into the attribut mean
ss.mean_

array([2.99390805])

In [77]:
# Knowledge Check

# What value should I put into the standard scaler to make the equality below return 0

ss.transform([])

ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [78]:
#__SOLUTION__
ss.transform([ss.mean_])

array([[0.]])

In [79]:
# we can then use these attributes to transform objects
np.random.seed(42)
random_numbers = np.random.normal(3,1, 2)
random_numbers

array([3.49671415, 2.8617357 ])

In [80]:
ss.transform(random_numbers.reshape(-1,1))

array([[ 0.51708177],
       [-0.13592498]])

In [81]:
# We can also use a scaler on a DataFrame
series_1 = np.random.normal(3,1,1000)
series_2 = np.random.uniform(0,100, 1000)
df_2 = pd.DataFrame([series_1, series_2]).T
ss_df = StandardScaler()
ss_df.fit_transform(df_2)


array([[ 0.63918361, -1.63325007],
       [ 1.53240185,  1.50265028],
       [-0.260668  , -1.56258467],
       ...,
       [ 0.56254398, -1.61544876],
       [ 1.40620165, -1.36827099],
       [ 0.92178475, -0.56807826]])

In [82]:
ss_df.transform([[5, 50]])

array([[ 2.01911307, -0.00948621]])

## Pair Exercise: One-hot Encoder

Another object that you will use often is OneHotEncoder from sklearn. It is recommended over pd.get_dummies() because it can trained, with the learned informed stored in the attributes of the object.

In [83]:
from sklearn.preprocessing import OneHotEncoder

In [84]:
np.random.seed(42)
# Let's create a dataframe that has days of the week and number of orders. 

days = np.random.choice(['m','t', 'w','th','f','s','su'], 1000)
orders = np.random.randint(0,1000,1000)

df = pd.DataFrame([days, orders]).T
df.columns = ['days', 'orders']
df.head()

days orders
0   su    758
1   th    105
2    f    562
3   su     80
4    w    132

Let's interact with an important parameters which we can pass when instantiating the OneHotEncoder object:` drop`.  

By dropping column, we avoid the [dummy variable trap](https://en.wikipedia.org/wiki/Dummy_variable_(statistics)).  

By passing `drop = True`, sklearn drops the first category it happens upon.  In this case, that is 'su'.  But what if we want to drop 'm'.  We can pass an array like object in as parameter to specify which column to drop.




In [85]:
# Instantiate the OHE object with a param that tells it to drop Monday
ohe = None

In [86]:
#__SOLUTION__
# Instantiate a OneHotEncoder object

ohe = OneHotEncoder(drop=['m'])

In [87]:
# Now, fit_transform the days column of the dataframe

ohe_array = None

In [316]:
#__SOLUTION__
ohe_matrix = ohe.fit_transform(df[['days']])

In [318]:
# look at __dict__ and checkout drop_idx_
# did it do what you wanted it to do?
ohe.__dict__

{'categories': 'auto',
 'sparse': True,
 'dtype': numpy.float64,
 'handle_unknown': 'error',
 'drop': array(['m'], dtype=object),
 'categories_': [array(['f', 'm', 's', 'su', 't', 'th', 'w'], dtype=object)],
 'drop_idx_': array([1])}

In [319]:
# check out the categories_ attribute
ohe.categories_

[array(['f', 'm', 's', 'su', 't', 'th', 'w'], dtype=object)]

In [320]:
# Check out the object itself
ohe_matrix

<1000x6 sparse matrix of type '<class 'numpy.float64'>'
	with 844 stored elements in Compressed Sparse Row format>

It is a sparse matrix, which is a matrix that is composed mostly of zeros

In [321]:
# We can convert it to an array like so
oh_df = pd.DataFrame.sparse.from_spmatrix(ohe_matrix)

In [322]:
# Now, using the categories_ attribute, set the column names to the correct days of the week
# you can use drop_idx_ for this as well



In [323]:
#__SOLUTION__
ohe_columns = list(ohe.categories_[0])
ohe_columns.pop(int(ohe.drop_idx_))
oh_df.columns = ohe_columns
oh_df.head()
oh_df.columns = ohe_columns
oh_df.head()

f    s   su    t   th    w
0  0.0  0.0  1.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  1.0  0.0
2  1.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  1.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  1.0

In [326]:
# Add the onehotencoded columns to the original df, and drop the days column


In [325]:
#__SOLUTION__
# Now, add the onehotencoded columns to the original df, and drop the days column

df = df.join(oh_df).drop('days', axis=1)
df.head()

orders    f    s   su    t   th    w
0    758  0.0  0.0  1.0  0.0  0.0  0.0
1    105  0.0  0.0  0.0  0.0  1.0  0.0
2    562  1.0  0.0  0.0  0.0  0.0  0.0
3     80  0.0  0.0  1.0  0.0  0.0  0.0
4    132  0.0  0.0  0.0  0.0  0.0  1.0